### ISSUE TITLE
mDNS .local address not working

### ISSUE THREAD

**Issue by roger-** [nirui/sshwifty#180]
I'm trying to connect to a server named `server.local` and I get this error:

```
Connection failed
dial tcp: lookup server.local on 127.0.0.11:53: no such host
```

Connecting via IP works though. Any ideas?

I'm using sshwifty via docker compose (self signed):

```yaml
version: '2.1'
services:
  sshwifty:
    image: niruix/sshwifty:latest
    container_name: sshwifty
    hostname: sshwifty
    environment:
      - TZ=xxx
      - SSHWIFTY_CONFIG=/etc/sshwifty/sshwifty.conf.json
    volumes:
      - ./config/sshwifty.conf.json:/etc/sshwifty/sshwifty.conf.json
      - ./config:/ssl
    ports:
      - 8182:8182
    restart: unless-stopped
```
