### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by SAOPP** [nirui/sshwifty#49]
Hi!

I have some trouble with the transfer of the configuration file to the container, container can't find my config, I'am doing something wrong in the path I think. Not sure, but I also has trying with envars, and after deploy, I can't login with my preset sharedkey. Could you point out a mistake?

Here is my stack:
```
version: '2.1'
services:

  sshwifty:
    image: niruix/sshwifty:latest
    container_name: sshwifty
    hostname: sshwifty
    environment:
      - TZ=Europe/Kiev
      - SSHWIFTY_CONFIG=/etc/sshwifty/sshwifty.conf.json
    volumes:
      - /mnt/docker_storage/sshwifty/sshwifty.conf.json:/etc/sshwifty/sshwifty.conf.json
    ports:
      - 8182:8182
    restart: unless-stopped
```

**Comment by nirui** [comment]
Hello.

I don't see any problem in the compose file. So maybe: 

* Check the permission of `/mnt/docker_storage/sshwifty/sshwifty.conf.json` to make sure it can be read by guests? 
* Take look what's inside `/mnt/docker_storage/sshwifty`. See if there is any weird folder docker created (Docker will automatically create a folder for the mount source if it does not exist)
* Take look what the log says via command such as `docker logs sshwifty`, it may contain helpful information.

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/118453880-61957580-b700-11eb-96c0-211c9076836b.png)

![image](https://user-images.githubusercontent.com/5647009/118453930-6fe39180-b700-11eb-8e05-23932db6d4a8.png)

**Comment by SAOPP** [comment]
I dunno what I do wrong.

**Comment by SAOPP** [comment]
```
[WRN] Mon, 17 May 2021 08:28:24 UTC Sshwifty > Configuration > Redundant: Unable to load configuration from "File": invalid character '/' looking for beginning of object key string
```

**Comment by nirui** [comment]
About the `is a directory` error: You might want to check to see if `/mnt/docker_storage/sshwifty/sshwifty.conf.json` exists, and there is no folder has the same name. The problem should go away after you deleted the `/mnt/docker_storage/sshwifty/sshwifty.conf.json` *folder*.

As for the `invalid character '/'` error, it indicates that there is an invalid character in the configuration file.

**Comment by SAOPP** [comment]
> About the `is a directory` error: You might want to check to see if `/mnt/docker_storage/sshwifty/sshwifty.conf.json` exists, and there is no folder has the same name. The problem should go away after you deleted the `/mnt/docker_storage/sshwifty/sshwifty.conf.json` _folder_.

'bout this, I mixed up my instances, sorry...

> As for the `invalid character '/'` error, it indicates that there is an invalid character in the configuration file.

'bout this, yes, I understood this, but where is this character I dunno - just copyed your example at finally, and the sate error there :|

**Comment by nirui** [comment]
You mean the error will happen even if you applied the `sshwifty.conf.example.json`? Hmm, that's weird. Can you do a `cat /mnt/docker_storage/sshwifty/sshwifty.conf.json` to see if the content of the config file is normal?

Also, if the end goal is to setup the Sshwifty login password, you can use `--env SSHWIFTY_SHAREDKEY="THE_PASSWORD"` parameter when starting up the container. The whole command should look like the following:

	docker run --detach \
	  --restart always \
	  --publish 8182:8182 \
	  --name sshwifty \
	  --env SSHWIFTY_SHAREDKEY="THE_PASSWORD" \
	  niruix/sshwifty:latest

or, for docker compose:

    environment:
      - TZ=Europe/Kiev
      - SSHWIFTY_SHAREDKEY=THE_PASSWORD

**Comment by SAOPP** [comment]
The end goals is starting the app :)

And I trying without config file and only evars... the result is... I can;t login with preshared key.


```
,
 Sshwifty Web SSH Client 
,

,
 Copyright (C) NI Rui <ranqus@gmail.com>
,
 https://github.com/nirui/sshwifty
,

,
[INF] Tue, 18 May 2021 09:04:18 UTC Sshwifty: Initializing
,
[INF] Tue, 18 May 2021 09:04:18 UTC Sshwifty > Configuration > Redundant: Loading configuration from one of the default configuration files ...
,
[WRN] Tue, 18 May 2021 09:04:18 UTC Sshwifty > Configuration > Redundant: Unable to load configuration from "File": Configuration file was not specified. Also tried fallback files "/home/sshwifty/.config/sshwifty.conf.json", "/etc/sshwifty.conf.json", "/sshwifty.conf.json", but none of it was available
,
[INF] Tue, 18 May 2021 09:04:18 UTC Sshwifty > Configuration > Redundant: Loading configuration from environment variables ...
,
[INF] Tue, 18 May 2021 09:04:18 UTC Sshwifty > Server (0.0.0.0:8182): Serving
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58968): Request completed: /
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58970): Request completed: /sshwifty/assets/333741748c30b12d24c5.js
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58972): Request completed: /sshwifty/assets/8d6257c7299a988a1df0.js
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58968): Request completed: /sshwifty/assets/009c25b35ba0a63a0e30.css
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58972): Request completed: /sshwifty/assets/b8d6796d634b834b19dc.js
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58970): Request completed: /sshwifty/assets/637a71bf488e59c7740d.js
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58974): Request completed: /sshwifty/assets/badb5115be9290c5b735.js
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58976): Request completed: /sshwifty/assets/9da92ca7d10a8d06fb31.js
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58978): Request completed: /sshwifty/assets/e4984861fbcd7e1be916.js
,
[INF] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58968): Request completed: /sshwifty/assets/b13087b32b4cfbf16622.js
,
[WRN] Tue, 18 May 2021 09:04:37 UTC Sshwifty > Server (0.0.0.0:8182) > Client (192.168.0.21:58974): Request ended with error: /sshwifty/socket/verify: HTTP Error (403): To use Websocket interface, a valid Auth Key must be provided
,
```

```
version: '2.1'
services:

  sshwifty:
    image: niruix/sshwifty:latest
    container_name: sshwifty
    hostname: sshwifty
    environment:
      - TZ=Europe/Kiev
      #- SSHWIFTY_CONFIG=/etc/sshwifty/sshwifty.conf.json
      - SSHWIFTY_SHAREDKEY=thepass
    #volumes:
      #- /mnt/docker_storage/sshwifty/sshwifty.conf.json/:/etc/sshwifty/sshwifty.conf.json/
    ports:
      - 8182:8182
    restart: unless-stopped
```

![image](https://user-images.githubusercontent.com/5647009/118624130-8c9bca00-b7d1-11eb-80c7-5565fab6184f.png)
